#!/bin/sh -eu
self="$(realpath -- "$0" || printf %s "$0")"

: "${file:=/dev/mem}"

found=0
for arg; do
  shift
  case "$found,$arg" in
  0,-*) ;;
  0,*)
    offset="$arg"
    found=1
    continue
    ;;
  1,*)
    file="$arg"
    found=2
    continue
    ;;
  *) ;;
  esac
  set -- "$@" "$arg"
done

"$(dirname -- "$self")"/memdump "$offset" "$file" | xxd -o "$offset" "$@"
