#!/bin/sh -eu
self="$(realpath -- "$0" || printf %s "$0")"

: "${file:=/dev/mem}"

found_file=0 # 0, 1, i(gnore)
revert=
plain=
for arg; do
  shift
  case "$found_file,$arg" in
  i,*)
    found_file=0
    ;;
  0,-[cglnosR])
    found_file=i
    ;;
  ?,-r|?,-revert)
    revert=1
    ;;
  ?,-p|?,-ps|?,-postscript|?,-plain)
    plain=1
    ;;
  0,-*) ;;
  0,*)
    file="$arg"
    arg="-"
    found_file=1
    ;;
  *) ;;
  esac
  set -- "$@" "$arg"
done

if [ "$revert" ] && ! [ "$plain" ]; then
  printf '%s: %s\n' "$0" "error: can only use -r together with -p" >&2
  exit 2
fi

seek=0
found_seek=0
for arg; do
  shift
  case "$found_seek,$arg" in
  0,-s)
    arg="-o"
    found_seek=1
    if [ "$revert" ]; then
      continue
    fi
    ;;
  0,-s*)
    seek="${arg#-s}"
    arg="-o$seek"
    if [ "$revert" ]; then
      continue
    fi
    ;;
  1,*)
    seek="$arg"
    found_seek=0
    if [ "$revert" ]; then
      continue
    fi
    ;;
  *) ;;
  esac
  set -- "$@" "$arg"
done

if [ "$revert" ]; then
  xxd "$@" | "$(dirname -- "$self")"/memdump -r "$seek" "$file"
else
  "$(dirname -- "$self")"/memdump "$seek" "$file" | xxd -o "$seek" "$@"
fi
